### ISSUE TITLE
Null Pointer while POS-Tagging

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#130]
`java.lang.NullPointerException
	at org.exmaralda.tagging.SextantIntegrator.integrate(SextantIntegrator.java:113)
	at org.exmaralda.tagging.CorpusTreeTagger.processTranscription(CorpusTreeTagger.java:64)
	at org.exmaralda.exakt.exmaraldaSearch.COMACorpusWalker.walk(COMACorpusWalker.java:66)
	at org.exmaralda.tagging.CorpusTreeTagger.tagCorpus(CorpusTreeTagger.java:76)
	at org.exmaralda.coma.actions.TreeTaggerAction$1.run(TreeTaggerAction.java:98)`

Test case: BOLSA Mini Demo Corpus

**Comment by berndmoos** [comment]
integrator now checks for speaker nullinger and continues if if speaker is null
