### ISSUE TITLE
BAS Player on the MAC: Mixer not supported

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#186]
`(1b) PartiturTableWithActions: setupMedia
This is the BASAudioPlayer setting media file to
/Users/runaragnarok/Desktop/EnglishTranslator.wav
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException:
Mixer not supported: null
    at javax.sound.sampled.AudioSystem.getMixer(AudioSystem.java:259)
    at ipsk.audio.player.Player.open(Player.java:387)
    at org.exmaralda.partitureditor.sound.BASAudioPlayer.setSoundFile(BASAudioPlayer.java:71)
    at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.setupMedia(PartitureTableWithActions.java:2057)`

The exception is thrown, but apparently not displayed in the PE. This may be because it is an instance of RuntimeException. Need to find the cause or at least catch it properly. See Ticket#2019032710000042. 

Observed on MAC OS 10.13

**Comment by berndmoos** [comment]
see #199, no use in working on this separately
