### ISSUE TITLE
Tier context menu won't appear on last tier?

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#187]
`Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Vector.elementData(Vector.java:734)
	at java.util.Vector.elementAt(Vector.java:477)
	at org.exmaralda.partitureditor.jexmaralda.Timeline.getTimelineItemAt(Timeline.java:54)
	at org.exmaralda.partitureditor.partiture.AbstractTranscriptionTableModel.containsEvent(AbstractTranscriptionTableModel.java:457)
	at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.popupMenuWillBecomeVisible(PartitureTableWithActions.java:2649)
	at javax.swing.JPopupMenu.firePopupMenuWillBecomeVisible(JPopupMenu.java:682)
	at javax.swing.JPopupMenu.setVisible(JPopupMenu.java:789)
	at javax.swing.JPopupMenu.show(JPopupMenu.java:965)
	at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.processMouseEvent(PartitureTableWithActions.java:390)
	at com.klg.jclass.table.CellArea.processMouseEvent(Unknown Source)
`

**Comment by berndmoos** [comment]
Fixed in about 5 minutes, took half a day to get the build process working after system upgrade...
