### ISSUE TITLE
GAT+HTML5 Audio Export: catch exception when no audio is assigned

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#20]
org.jdom.IllegalDataException: The data "null" is not legal for a JDOM attribute: A null is not a legal XML value.
    at org.jdom.Attribute.setValue(Attribute.java:491)
    at org.jdom.Attribute.<init>(Attribute.java:228)
    at org.jdom.Attribute.<init>(Attribute.java:251)
    at org.jdom.Element.setAttribute(Element.java:1149)
    at org.exmaralda.partitureditor.jexmaralda.segment.GATSegmentation.toXML(GATSegmentation.java:281)

**Comment by berndmoos** [comment]
Fixed. An adequate error message is now given when no WAV audio is assigned, output is aborted.
