### ISSUE TITLE
New Linux distribution

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#238]
... with OpenJDK 11+, 64bit, ideally using jpackage. This can only be done from Linux itself, not from Windows. 

From https://www.baeldung.com/java14-jpackage: 

> RPM, DEB on Linux: On Red Hat Linux, we need the rpm-build package; on Ubuntu Linux, we need the fakeroot package

**Comment by Herrner** [comment]
I can't get a f**king working development environment up here. Does GitHub have epics? We still need a dependency epic.

**Comment by Herrner** [comment]
```log
========= LOG FILE CUT Thu Dec 03 09:51:35 CET 2020===============
ar:/home/kai/IdeaProjects/exmaralda/lib/jctable.jar:/home/kai/IdeaProjects/exmaralda/lib/elan-5.8.jar:/home/kai/IdeaProjects/exmaralda/lib/weblicht.jar:/home/kai/IdeaProjects/exmaralda/lib/serializer.jar:/home/kai/IdeaProjects/exmaralda/lib/stax-utils.jar:/home/kai/IdeaProjects/exmaralda/lib/xercesImpl.jar:/home/kai/IdeaProjects/exmaralda/lib/ips.commons.jar:/home/kai/IdeaProjects/exmaralda/lib/jaxen-1.1.6.jar:/home/kai/IdeaProjects/exmaralda/lib/jcalendar-1.4.jar:/home/kai/IdeaProjects/exmaralda/lib/commons-io-2.4.jar:/home/kai/IdeaProjects/exmaralda/lib/httpcore-4.4.3.jar:/home/kai/IdeaProjects/exmaralda/lib/httpmime-4.5.1.jar:/home/kai/IdeaProjects/exmaralda/lib/ips.audiotools.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-base-11.jar:/home/kai/IdeaProjects/exmaralda/lib/jaxb-api-2.3.0.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-media-11.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-swing-11.jar:/home/kai/IdeaProjects/exmaralda/lib/commons-lang-2.5.jar:/home/kai/IdeaProjects/exmaralda/lib/httpclient-4.5.1.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-base-11-win.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-controls-11.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-graphics-11.jar:/home/kai/IdeaProjects/exmaralda/lib/commons-logging-1.2.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-media-11-win.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-swing-11-win.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-controls-11-win.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-graphics-11-win.jar
Java Library Path: /home/kai/IdeaProjects/exmaralda/lib
Application name :Partitur-Editor
Application version :1.7
Build time :20201201.1639
http://www.exmaralda.org
*********************************
Default player: BAS-Audio-Player
User's player: BAS-Audio-Player
started reading Internationalization file...
Internationalization file read.
Initializing search dialog
started reading document...
document read.
Search dialog initialized
started reading document...
document read.
TIME: 78
TIME2: 56
TIME3: 42
TIMEX: 196
Application initialized.
Default player: BAS-Audio-Player
started reading document...
document read.
Settings read and set.
Data reset started at Thu Dec 03 09:49:16 CET 2020
Data reset done at Thu Dec 03 09:49:16 CET 2020
This is AudioPanel.formComponentResized.
This is AudioPanel.formComponentResized.
editPreferencesAction!
Changed player type settings to JavaFX-Player
Settings stored.
Application terminated. 
Thu Dec 03 09:49:31 CET 2020
________________________
************* INFO **************
Date : Thu Dec 03 09:49:40 CET 2020
Operating system : Linux
Operating system architecture : amd64
OS version : 5.8.0-31-generic
JRE version : 14.0.2
JRE vendor : Private Build
JVM version (specification/implementation) : 14 / 14.0.2+12-Ubuntu-1
org.sfb538.exmaralda.PartiturEditor.PlayerType: JavaFX-Player
Java Class Path : /home/kai/IdeaProjects/exmaralda/out/production/exmaralda:/home/kai/IdeaProjects/exmaralda/lib/jdom.jar:/home/kai/IdeaProjects/exmaralda/lib/tt4j.jar:/home/kai/IdeaProjects/exmaralda/lib/BATIK.jar:/home/kai/IdeaProjects/exmaralda/lib/xalan.jar:/home/kai/IdeaProjects/exmaralda/lib/bounce.jar:/home/kai/IdeaProjects/exmaralda/lib/saxon9.jar:/home/kai/IdeaProjects/exmaralda/lib/jctable.jar:/home/kai/IdeaProjects/exmaralda/lib/elan-5.8.jar:/home/kai/IdeaProjects/exmaralda/lib/weblicht.jar:/home/kai/IdeaProjects/exmaralda/lib/serializer.jar:/home/kai/IdeaProjects/exmaralda/lib/stax-utils.jar:/home/kai/IdeaProjects/exmaralda/lib/xercesImpl.jar:/home/kai/IdeaProjects/exmaralda/lib/ips.commons.jar:/home/kai/IdeaProjects/exmaralda/lib/jaxen-1.1.6.jar:/home/kai/IdeaProjects/exmaralda/lib/jcalendar-1.4.jar:/home/kai/IdeaProjects/exmaralda/lib/commons-io-2.4.jar:/home/kai/IdeaProjects/exmaralda/lib/httpcore-4.4.3.jar:/home/kai/IdeaProjects/exmaralda/lib/httpmime-4.5.1.jar:/home/kai/IdeaProjects/exmaralda/lib/ips.audiotools.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-base-11.jar:/home/kai/IdeaProjects/exmaralda/lib/jaxb-api-2.3.0.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-media-11.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-swing-11.jar:/home/kai/IdeaProjects/exmaralda/lib/commons-lang-2.5.jar:/home/kai/IdeaProjects/exmaralda/lib/httpclient-4.5.1.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-base-11-win.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-controls-11.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-graphics-11.jar:/home/kai/IdeaProjects/exmaralda/lib/commons-logging-1.2.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-media-11-win.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-swing-11-win.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-controls-11-win.jar:/home/kai/IdeaProjects/exmaralda/lib/javafx-graphics-11-win.jar
Java Library Path: /home/kai/IdeaProjects/exmaralda/lib
Application name :Partitur-Editor
Application version :1.7
Build time :20201201.1639
http://www.exmaralda.org
*********************************
Default player: BAS-Audio-Player
User's player: JavaFX-Player
started reading Internationalization file...
Internationalization file read.
Initializing search dialog
started reading document...
document read.
Search dialog initialized
started reading document...
document read.
TIME: 72
TIME2: 52
TIME3: 43
TIMEX: 192
Application initialized.
Default player: BAS-Audio-Player
started reading document...
document read.
Settings read and set.
Data reset started at Thu Dec 03 09:49:42 CET 2020
Data reset done at Thu Dec 03 09:49:42 CET 2020
This is AudioPanel.formComponentResized.
This is AudioPanel.formComponentResized.
OpenRecentAction!
started reading document...
document read.
Started sorting tier...
Tier sorting finished.
Started sorting tier...
Tier sorting finished.
Firing data reset... Thu Dec 03 09:49:51 CET 2020
Data reset started at Thu Dec 03 09:49:51 CET 2020
Data reset done at Thu Dec 03 09:49:51 CET 2020
(1a) PartiturTableWithActions: setupMedia
(2) PartiturEditor: setupMedia
##############/home/kai/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_PCM_WAV.wav
Information from header of wav-file:
NrOfChannels    : 2
Sample frequency: 48000
Bitrate         : 16
nrOfSamples     : 1027200
 -> Length      : 21400
WAVE Format     : PCM (uncompressed)
started reading Internationalization file...
Internationalization file read.
Locale: deu
(1b) PartiturTableWithActions: setupMedia
This is the JavaFXPlayer setting media file to /home/kai/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-1.mpg
******* URLString=file:////home/kai/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-1.mpg
Dez. 03, 2020 9:49:51 AM mpi.eudico.client.annotator.player.JFXMediaPlayer <init>
INFORMATION: JFXMediaPlayer URL: file:/home/kai/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-1.mpg
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:234)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:234)
	at java.base/java.lang.Thread.run(Thread.java:832)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.exmaralda.partitureditor.sound.JavaFXPlayer.play(JavaFXPlayer.java:113)
	at org.exmaralda.partitureditor.sound.JavaFXPlayer.startPlayback(JavaFXPlayer.java:118)

[...]

**Comment by berndmoos** [comment]
`
java.lang.module.FindException: Hash of jdk.management.jfr (e02522b71006de2e5f5cfb4b62b3ed4af7659bef52f6ec55df0c1abce130e286) differs to expected hash (9ac607490568ac60259af12ac34079b00adeac59f154d5bb90dd9e2ecc8f022f) recorded in java.base
`
https://github.com/AdoptOpenJDK/openjdk-support/issues/165

(But I'm not using AdoptOpenJDK, should I?)

**Comment by berndmoos** [comment]
's better with AdoptOpenJDK (and after installing some more things). This is a first result:

https://www.exmaralda.org/files/prevDL/partitureditor_1.7-1_amd64.deb

I can install the PE locally with it, and it's running under opt/partitureditor

@Herrner and @nolda : would that be an okay way to distribute EXMARaLDA for Linux (Ubuntu)?

**Comment by berndmoos** [comment]
... and an attempt to get the tar.gz version with shell scripts (right now: only PE and FOLKER) working in the new setup. See https://exmaralda.org/en/preview-version/

**Comment by berndmoos** [comment]
With the newest shell scripts (in the tar.gz version), all of the tools can be started via the terminal. Not tested yet: do they really work?

**Comment by berndmoos** [comment]
> all of the tools 

@Herrner : All of them! Really!

![image](https://user-images.githubusercontent.com/13796493/102115018-3a7a0580-3e3b-11eb-821d-680539acd24f.png)

**Comment by berndmoos** [comment]
Still open somehow, but see #294, #283 and #246.

**Comment by hannahedeland** [comment]
Sorry, I'm confused, the .deb is not linked on the website (it's commented out), but mentioned, I just took the tar.gz version now, do we need to test both...?

**Comment by berndmoos** [comment]
> Sorry, I'm confused, the .deb is not linked on the website (it's commented out), but mentioned, I just took the tar.gz version now, do we need to test both...?

Deb packages can only be built on a Linux machine, and I haven't had one for about 4 months now...

**Comment by berndmoos** [comment]
I have a Mint Linux Machinche and I am not afraid to use it. 

Related issues are: #339, #326, #291, #246, #199, #59, #44

**Comment by berndmoos** [comment]
@Herrner : I'm afraid, I need the tool icons (and the document icons?) in PNG format. Default size seems to be 64px.

Or can I just convert the Windows *.ico files?

**Comment by Herrner** [comment]
Wher do you need them? `/build/linux/icons` ?

**Comment by berndmoos** [comment]
> Wher do you need them? `/build/linux/icons` ?

I found 256x256 or 512x512 PNGs and downsized them to 64x64. They're currently in build/png-icons

**Comment by berndmoos** [comment]
Hooray. I can build a deb package.
Kawestions to Kawanna (@Herrner):
- do I also build an RPM something? Is it good for anything?
- do we still need a tar.gz version?
- is it better to pack all tools into one (as on Windows) or not (as on the Mac)?

**Comment by Herrner** [comment]
If it's not much work, RPMs won't hurt (for the Fedora Linux / SuSe users). Don't know about the `tar.gz`, but that should work on any distro methinks. As for the packaging: I don't know. If the tools share one VM, then it might be a good idea.

**Comment by berndmoos** [comment]
N.B.: Cannot build an RPM package from Mint Linux, and, no, I am not getting another computer to install Fedora or SuSe. Instead, will build a good old gnuzipped tarball.

**Comment by berndmoos** [comment]
We totally have a new linux distribution now
