### ISSUE TITLE
JavaFX-Player not working on Linux

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#246]
Error when trying to initialise video image, see https://stackoverflow.com/questions/65173104/javafx-gtk-throws-java-lang-nosuchmethoderror-getperspectivetransformnoclone

**Comment by berndmoos** [comment]
Sumfn todo with that?

vmArgs = ['-Djdk.gtk.version=2'] // required due to a bug in Java: https://github.com/javafxports/openjdk-jfx/issues/175

**Comment by berndmoos** [comment]
Oh Lord won't you buy me a Linux machine? So I can test this? @Herrner : worketh it on your Linux machine?

**Comment by hannahedeland** [comment]
Maybe it's me, but it seems something's missing?
```
************* INFO **************
Date : Wed Jan 12 09:44:46 CET 2022
Operating system : Linux
Operating system architecture : amd64
OS version : 5.4.0-91-generic
JRE version : 11.0.13
JRE vendor : Eclipse Adoptium
JVM version (specification/implementation) : 11 / 11.0.13+8
org.sfb538.exmaralda.PartiturEditor.PlayerType: JavaFX-Player
Java Class Path : /home/hanna/Downloads/exmaralda1.13/lib/EXMARaLDA.jar:/home/hanna/Downloads/exmaralda1.13/lib/jctable.jar:/home/hanna/Downloads/exmaralda1.13/lib/jdom.jar:/home/hanna/Downloads/exmaralda1.13/lib/xalan.jar:/home/hanna/Downloads/exmaralda1.13/lib/xercesImpl.jar:/home/hanna/Downloads/exmaralda1.13/lib/saxon9.jar:/home/hanna/Downloads/exmaralda1.13/lib/saxon9-dom.jar:/home/hanna/Downloads/exmaralda1.13/lib/serializer.jar:/home/hanna/Downloads/exmaralda1.13/lib/jaxen-1.1.6.jar:/home/hanna/Downloads/exmaralda1.13/lib/jaxb-api-2.3.0.jar:/home/hanna/Downloads/exmaralda1.13/lib/ips.audiotools.jar:/home/hanna/Downloads/exmaralda1.13/lib/ips.commons.jar:/home/hanna/Downloads/exmaralda1.13/lib/elan-5.8.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx-base-11.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx-base-11-linux.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx-controls-11.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx-graphics-11.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx-graphics-11-linux.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx-media-11.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx-media-11-linux.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx-swing-11.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx-swing-11-linux.jar:/home/hanna/Downloads/exmaralda1.13/lib/httpcore-4.4.3.jar:/home/hanna/Downloads/exmaralda1.13/lib/httpclient-4.5.1.jar:/home/hanna/Downloads/exmaralda1.13/lib/httpmime-4.5.1.jar:/home/hanna/Downloads/exmaralda1.13/lib/commons-logging-1.2.jar:/home/hanna/Downloads/exmaralda1.13/lib/BATIK.jar:/home/hanna/Downloads/exmaralda1.13/lib/tt4j.jar:/home/hanna/Downloads/exmaralda1.13/lib/weblicht.jar
Java Library Path: /home/hanna/Downloads/exmaralda1.13/lib
Application name :Partitur-Editor
Application version :1.7
Build time :20220106.1654
http://www.exmaralda.org
*********************************
Default player: BAS-Audio-Player
User's player: JavaFX-Player
started reading Internationalization file...
Internationalization file read.
Initializing search dialog
started reading document...
document read.
Search dialog initialized
started reading document...
document read.
TIME: 61
TIME2: 32
TIME3: 78
TIMEX: 195
Application initialized.
Default player: BAS-Audio-Player
started reading document...
document read.
Found 1 auto save files
Settings read and set.
Data reset started at Wed Jan 12 09:44:49 CET 2022
Data reset done at Wed Jan 12 09:44:49 CET 2022
This is AudioPanel.formComponentResized.
This is AudioPanel.formComponentResized.
editRecordingsAction!
(1a) PartiturTableWithActions: setupMedia
(2) PartiturEditor: setupMedia
This is the BASAudioPlayer setting media file to /home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-4.mp4
java.io.IOException: BASAudioPlayer can only be used with *.wav files.
(1b) PartiturTableWithActions: setupMedia
This is the JavaFXPlayer setting media file to /home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-4.mp4
******* URLString=file:////home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-4.mp4
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
at org.exmaralda.partitureditor.sound.JavaFXPlayer.setSoundFile(JavaFXPlayer.java:64)
at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.setupMedia(PartitureTableWithActions.java:2158)
at org.exmaralda.partitureditor.partiture.transcriptionActions.EditRecordingsAction.editRecordings(EditRecordingsAction.java:41)
at org.exmaralda.partitureditor.partiture.transcriptionActions.EditRecordingsAction.actionPerformed(EditRecordingsAction.java:30)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
at java.desktop/java.awt.Component.processEvent(Component.java:6400)
at java.desktop/java.awt.Container.processEvent(Container.java:2263)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
... 49 more
```

**Comment by berndmoos** [comment]
Looks like javafx itself is missing, but it seems to be on the classpath... Need to check what's in the tar.gz file.

**Comment by berndmoos** [comment]
The java-fx-\*.jars are in the lib folder of the distribution, but they only contain a manifest, no compiled class files. Why?? Probably because I am now building from Windows, and the assumption that everything java-fx-\* without \* == mac|win is for all systems is wrong (or: it is for all systems, but it is empty). So I need a Linux JDK with java-fx-\* in it, unpack it and include just the relevant jars in the distribution. Urgh. 

https://stackoverflow.com/questions/22514310/whats-the-location-of-the-javafx-runtime-jar-file-jfxrt-jar-on-linux

**Comment by berndmoos** [comment]
Here is a page where Java-FX-SDKs can be downloaded for all operating systems with different architectures:

https://gluonhq.com/products/javafx/

If it's just for Linux, I would need to understand which architecture is the most common one and integrate the respective jars (and \*.so files which are probably the native interface libraries). So aarch64, x64 or arm32 (probably not, 32 is history)? The things knower says that it is **x64**!

Then again: this seems to be an active project and version 17 of the JDK is very recent (October 2021). If things with the JavaFX player do not work well on Windows (where I have integrated some random version of JavaFX), it might be worth trying a newer version from this site.

For now: I will try to make a new Linux build with the version 17 jars etc. integrated.

For later or never: a new issue for "keep Java FX up to date".

**Comment by berndmoos** [comment]
@hannahedeland and @Herrner : the newest preview has (1) the correct JavaFX jars integrated, (2) the build scripts changed accordingly and (3) the Linux case accounted for when initialising the player (so the BASAudioPlayer error message should go away). There are still warnings in the log, but maybe they are not relevant. If you can, please check: can the Partitur-Editor open and play an MPEG-4 video with the JavaFX-Player?

**Comment by hannahedeland** [comment]
```
************* INFO **************
Date : Fri Jan 14 13:29:24 CET 2022
Operating system : Linux
Operating system architecture : amd64
OS version : 5.4.0-91-generic
JRE version : 11.0.13
JRE vendor : Eclipse Adoptium
JVM version (specification/implementation) : 11 / 11.0.13+8
org.sfb538.exmaralda.PartiturEditor.PlayerType: JavaFX-Player
Java Class Path : /home/hanna/Downloads/exmaralda1.13/lib/EXMARaLDA.jar:/home/hanna/Downloads/exmaralda1.13/lib/jctable.jar:/home/hanna/Downloads/exmaralda1.13/lib/jdom.jar:/home/hanna/Downloads/exmaralda1.13/lib/xalan.jar:/home/hanna/Downloads/exmaralda1.13/lib/xercesImpl.jar:/home/hanna/Downloads/exmaralda1.13/lib/saxon9.jar:/home/hanna/Downloads/exmaralda1.13/lib/saxon9-dom.jar:/home/hanna/Downloads/exmaralda1.13/lib/serializer.jar:/home/hanna/Downloads/exmaralda1.13/lib/jaxen-1.1.6.jar:/home/hanna/Downloads/exmaralda1.13/lib/jaxb-api-2.3.0.jar:/home/hanna/Downloads/exmaralda1.13/lib/ips.audiotools.jar:/home/hanna/Downloads/exmaralda1.13/lib/ips.commons.jar:/home/hanna/Downloads/exmaralda1.13/lib/elan-6.2.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx.base.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx.controls.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx.media.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx.swing.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx.graphics.jar:/home/hanna/Downloads/exmaralda1.13/lib/httpcore-4.4.3.jar:/home/hanna/Downloads/exmaralda1.13/lib/httpclient-4.5.1.jar:/home/hanna/Downloads/exmaralda1.13/lib/httpmime-4.5.1.jar:/home/hanna/Downloads/exmaralda1.13/lib/commons-logging-1.2.jar:/home/hanna/Downloads/exmaralda1.13/lib/BATIK.jar:/home/hanna/Downloads/exmaralda1.13/lib/tt4j.jar:/home/hanna/Downloads/exmaralda1.13/lib/weblicht.jar
Java Library Path: /home/hanna/Downloads/exmaralda1.13/lib
Application name :Partitur-Editor
Application version :1.7
Build time :20220114.1247
http://www.exmaralda.org
*********************************
Default player: BAS-Audio-Player
User's player: JavaFX-Player
started reading Internationalization file...
Internationalization file read.
Initializing search dialog
started reading document...
document read.
Search dialog initialized
started reading document...
document read.
TIME: 50
TIME2: 31
TIME3: 64
TIMEX: 162
Application initialized.
Default player: BAS-Audio-Player
started reading document...
document read.
Found 1 auto save files
Settings read and set.
Data reset started at Fri Jan 14 13:29:26 CET 2022
Data reset done at Fri Jan 14 13:29:26 CET 2022
This is AudioPanel.formComponentResized.
This is AudioPanel.formComponentResized.
editRecordingsAction!
(1a) PartiturEditor: setupMedia
(2) PartiturEditor: setupMedia
This is the BASAudioPlayer setting media file to /home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-4.mp4
BASAudioPlayer could not set file for TimeViewer
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.exmaralda.partitureditor.sound.BASAudioPlayer.getTotalLength(BASAudioPlayer.java:95)
	at org.exmaralda.folker.timeview.AbstractTimeProportionalViewer.setSoundFile(AbstractTimeProportionalViewer.java:165)
	at org.exmaralda.partitureditor.partiture.PartiturEditor.setupMedia(PartiturEditor.java:771)
	at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.setupMedia(PartitureTableWithActions.java:2153)
	at org.exmaralda.partitureditor.partiture.transcriptionActions.EditRecordingsAction.editRecordings(EditRecordingsAction.java:41)
	at org.exmaralda.partitureditor.partiture.transcriptionActions.EditRecordingsAction.actionPerformed(EditRecordingsAction.java:30)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
This is AudioPanel.formComponentResized.
```

**Comment by Herrner** [comment]
Theres some odd things happening with the preview. With JavaFX Player selected, the error message reappears when switching to a mpg1-file:
```
There was a problem opening the file:
/home/kai/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-1.mpg
General reasons for this error are that the file does not exist or it is in some format not supported by the current configuration.
Error message:
mpi.eudico.client.annotator.player.NoPlayerException: JFXMediaPlayer cannot handle the file: Unrecognized file signature!
You have currently set your player preference to: JavaFX-Player
Try one of the following: (1) Edit the recordings associated with this transcription (2) Use a different media player (Edit > Preferences > Media) 
Consult this document for further information on audio and video support in EXMARaLDA

```
and renders the Audi/Video panel useless/unresponsive.

**Comment by berndmoos** [comment]
My mistake: I checked the wrong string for os=linux. For clarification: only WAV (via BASPlayer) and MPEG-4 (via JavaFX-Player) can be played on Linux. There is no player available for any other format. With MPEG-1, the whole process should simply fail. If it doesn't, I'll have to check for file suffixes or something similar.

New preview!

**Comment by hannahedeland** [comment]
Now I can open and play the MP4 with the JavaFX-Player, but when playing intervals, each time some 0.x seconds of the following interval of the last played interval is inserted before the intended interval starts (which you probably won't notice if you play them all in order), i.e. if I would play the first, then the second and then again the first of the intervals aligned with the following events
`Hello | my name is | Tom! `
the result would be "To- Hello", which is not really optimal for transcribing, but maybe this is something I could get rid of by changing some settings etc., maybe @Herrner doesn't have this problem :)

```
________________________
************* INFO **************
Date : Fri Jan 14 17:19:17 CET 2022
Operating system : Linux
Operating system architecture : amd64
OS version : 5.4.0-91-generic
JRE version : 11.0.13
JRE vendor : Eclipse Adoptium
JVM version (specification/implementation) : 11 / 11.0.13+8
org.sfb538.exmaralda.PartiturEditor.PlayerType: JavaFX-Player
Java Class Path : /home/hanna/Downloads/exmaralda1.13/lib/EXMARaLDA.jar:/home/hanna/Downloads/exmaralda1.13/lib/jctable.jar:/home/hanna/Downloads/exmaralda1.13/lib/jdom.jar:/home/hanna/Downloads/exmaralda1.13/lib/xalan.jar:/home/hanna/Downloads/exmaralda1.13/lib/xercesImpl.jar:/home/hanna/Downloads/exmaralda1.13/lib/saxon9.jar:/home/hanna/Downloads/exmaralda1.13/lib/saxon9-dom.jar:/home/hanna/Downloads/exmaralda1.13/lib/serializer.jar:/home/hanna/Downloads/exmaralda1.13/lib/jaxen-1.1.6.jar:/home/hanna/Downloads/exmaralda1.13/lib/jaxb-api-2.3.0.jar:/home/hanna/Downloads/exmaralda1.13/lib/ips.audiotools.jar:/home/hanna/Downloads/exmaralda1.13/lib/ips.commons.jar:/home/hanna/Downloads/exmaralda1.13/lib/elan-6.2.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx.base.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx.controls.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx.media.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx.swing.jar:/home/hanna/Downloads/exmaralda1.13/lib/javafx.graphics.jar:/home/hanna/Downloads/exmaralda1.13/lib/httpcore-4.4.3.jar:/home/hanna/Downloads/exmaralda1.13/lib/httpclient-4.5.1.jar:/home/hanna/Downloads/exmaralda1.13/lib/httpmime-4.5.1.jar:/home/hanna/Downloads/exmaralda1.13/lib/commons-logging-1.2.jar:/home/hanna/Downloads/exmaralda1.13/lib/BATIK.jar:/home/hanna/Downloads/exmaralda1.13/lib/tt4j.jar:/home/hanna/Downloads/exmaralda1.13/lib/weblicht.jar
Java Library Path: /home/hanna/Downloads/exmaralda1.13/lib
Application name :Partitur-Editor
Application version :1.7
Build time :20220114.1537
http://www.exmaralda.org
*********************************
Default player: BAS-Audio-Player
User's player: JavaFX-Player
started reading Internationalization file...
Internationalization file read.
Initializing search dialog
started reading document...
document read.
Search dialog initialized
started reading document...
document read.
TIME: 48
TIME2: 31
TIME3: 86
TIMEX: 189
Application initialized.
Default player: BAS-Audio-Player
started reading document...
document read.
Found 1 auto save files
Settings read and set.
Data reset started at Fri Jan 14 17:19:20 CET 2022
Data reset done at Fri Jan 14 17:19:20 CET 2022
This is AudioPanel.formComponentResized.
This is AudioPanel.formComponentResized.
This is AudioPanel.formComponentResized.
openAction!
started reading document...
document read.
Firing data reset... Fri Jan 14 17:19:38 CET 2022
Data reset started at Fri Jan 14 17:19:38 CET 2022
Data reset done at Fri Jan 14 17:19:38 CET 2022
(1a) PartiturEditor: setupMedia
(2) PartiturEditor: setupMedia
Initialising timelineViewer
WaveFormViewer setting sound file to /home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_PCM_WAV.wav
##############/home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_PCM_WAV.wav
Information from header of wav-file:
NrOfChannels    : 2
Sample frequency: 48000
Bitrate         : 16
nrOfSamples     : 1027200
 -> Length      : 21400
WAVE Format     : PCM (uncompressed)
started reading Internationalization file...
Internationalization file read.
Locale: deu
(1b) PartiturTableWithActions: setupMedia
This is the JavaFXPlayer setting media file to /home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-1.mpg
******* URLString=file:////home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-1.mpg
Jan. 14, 2022 5:19:38 NACHM. mpi.eudico.client.annotator.player.JFXMediaPlayer <init>
INFORMATION: JFXMediaPlayer URL: file:////home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-1.mpg
Jan. 14, 2022 5:19:38 NACHM. com.sun.javafx.application.PlatformImpl startup
WARNUNG: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @32ebb77c'
Jan. 14, 2022 5:19:38 NACHM. mpi.eudico.client.annotator.player.JFXMediaPlayer <init>
INFORMATION: JFXMediaPlayer Media Exception: Unrecognized file signature!
Message: mpi.eudico.client.annotator.player.NoPlayerException: JFXMediaPlayer cannot handle the file: Unrecognized file signature!
editRecordingsAction!
(1a) PartiturEditor: setupMedia
(2) PartiturEditor: setupMedia
Initialising timelineViewer
WaveFormViewer setting sound file to /home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_PCM_WAV.wav
##############/home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_PCM_WAV.wav
Information from header of wav-file:
NrOfChannels    : 2
Sample frequency: 48000
Bitrate         : 16
nrOfSamples     : 1027200
 -> Length      : 21400
WAVE Format     : PCM (uncompressed)
(1b) PartiturTableWithActions: setupMedia
This is the JavaFXPlayer setting media file to /home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_PCM_WAV.wav
******* URLString=file:////home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_PCM_WAV.wav
Jan. 14, 2022 5:19:47 NACHM. mpi.eudico.client.annotator.player.JFXMediaPlayer <init>
INFORMATION: JFXMediaPlayer URL: file:////home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_PCM_WAV.wav
Jan. 14, 2022 5:19:47 NACHM. mpi.eudico.client.annotator.player.JFXMediaPlayer printMediaInfo
INFORMATION: Media Information:
Track: 0 audio/x-raw
name: audio/x-raw
encoding: PCM
enabled: false

(1b - alpha) - Media file is now set for player of PartiturTableWithActions
   Player says that media file has length 21.4
(1c) PartiturTableWithActions: handing the media file to the audio/video panel
(3a) AudioPanel: openSoundFile
(1a) PartiturEditor: setupMedia
(2) PartiturEditor: setupMedia
Initialising timelineViewer
WaveFormViewer setting sound file to /home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_PCM_WAV.wav
##############/home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_PCM_WAV.wav
Information from header of wav-file:
NrOfChannels    : 2
Sample frequency: 48000
Bitrate         : 16
nrOfSamples     : 1027200
 -> Length      : 21400
WAVE Format     : PCM (uncompressed)
(1b) PartiturTableWithActions: setupMedia
This is the JavaFXPlayer setting media file to /home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-4.mp4
******* URLString=file:////home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-4.mp4
Jan. 14, 2022 5:19:51 NACHM. mpi.eudico.client.annotator.player.JFXMediaPlayer stop
WARNUNG: Cannot pause player, status is: READY
Jan. 14, 2022 5:19:51 NACHM. mpi.eudico.client.annotator.player.JFXMediaPlayer <init>
INFORMATION: JFXMediaPlayer URL: file:////home/hanna/Downloads/MEDIA-TEST-BATTERY/BECKHAMS_MPEG-4.mp4
Jan. 14, 2022 5:19:51 NACHM. mpi.eudico.client.annotator.player.JFXMediaPlayer printMediaInfo
INFORMATION: Media Information:
Track: 1 video/x-h264
name: video/x-h264
video width: 496
encoding: H264
video height: 270
enabled: true
Track: 0 audio/mpeg
name: audio/mpeg
encoding: AAC
enabled: true

Jan. 14, 2022 5:19:51 NACHM. mpi.eudico.client.annotator.player.JFXMediaPlayer$1 run
INFORMATION: Setting up the Scene.
(1b - alpha) - Media file is now set for player of PartiturTableWithActions
   Player says that media file has length 21.4
(1c) PartiturTableWithActions: handing the media file to the audio/video panel
(3a) AudioPanel: openSoundFile
(3b) AudioPanel: taking care of the visual component
JavaFXPlayer says the movie BECKHAMS_MPEG-4.mp4 has width 496and  height 270
Preferred size set to: 480/261
(3c) AudioPanel: added the visual component
nl.mpi.jfx.JFXVideoPanel[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=480,height=261]]
(1d) PartiturTableWithActions: handling a video
This is AudioPanel.formComponentResized.
Current dimensions: [480/261]
Dimensions after resize: [479.0/261.0]
nl.mpi.jfx.JFXVideoPanel[,0,0,480x261,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=479,height=261]]
Firing playback stopped
Firing playback stopped
Firing playback stopped
Firing playback stopped
Firing playback stopped
```

**Comment by berndmoos** [comment]
It is working, and I do not care.
