### ISSUE TITLE
Make and test Linux distributions

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#30]
Hanna has made this a RedMine task for Timm, Niko, Tommi (?)

**Comment by berndmoos** [comment]
32bit or 64bit for libfobs / jre?

```
This is the JMFPlayer setting media file to /home/tpirinen/HZSK/Korpora/HZSK/EXMARaLDA-Demokorpus/RudiVoellerWutausbruch/RudiVoellerWutausbruch.mp3
Fobs4JMF - Native shared library NOT found
java.lang.UnsatisfiedLinkError: /home/tpirinen/test/exmaralda1.10/lib/libfobs4jmf.so: /home/tpirinen/test/exmaralda1.10/lib/libfobs4jmf.so: falsche ELF-Klasse: ELFCLASS32 (Possible cause: architecture word width `mismatch)
```

**Comment by berndmoos** [comment]
Initialise SVGPanel only when PartiturEditor is the parent (alternatively include BATIK.jar, but why init it when it is not needed?):

in FOLKER:

```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/apache/batik/swing/JSVGScrollPane
	at org.exmaralda.partitureditor.svgPanel.SVGDialog.<init>(SVGDialog.java:23)
	at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.initDialogs(PartitureTableWithActions.java:330)
	at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.<init>(PartitureTableWithActions.java:238)
	at org.exmaralda.folker.application.ApplicationControl.<init>(ApplicationControl.java:189)
	at org.exmaralda.folker.application.ApplicationFrame.<init>(ApplicationFrame.java:40)
```

... in EXAKT:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/batik/swing/JSVGScrollPane
	at org.exmaralda.partitureditor.svgPanel.SVGDialog.<init>(SVGDialog.java:23)
	at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.initDialogs(PartitureTableWithActions.java:330)
	at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.<init>(PartitureTableWithActions.java:238)
	at org.exmaralda.partitureditor.partiture.PartitureTableWithActions.<init>(PartitureTableWithActions.java:221)
	at org.exmaralda.exakt.exmaraldaSearch.swing.EXAKT.<init>(EXAKT.java:146)
	at org.exmaralda.exakt.exmaraldaSearch.swing.EXAKT.main(EXAKT.java:833)
```

**Comment by berndmoos** [comment]
It's not easy running 32bit java on Ubunut:

http://askubuntu.com/questions/454253/how-to-run-32-bit-app-in-ubuntu-64-bit

**Comment by berndmoos** [comment]
PE now running on XUBUNTU 16.04, 32bit on VM Player. FOBS player seems to be crap, fixing an issue with BAS player. Hold on.

**Comment by berndmoos** [comment]
Issues with BAS Player fixed.

**Comment by berndmoos** [comment]
Now three versions: 

- 32bit + Java + FOBSJMF
- 32bit + Java + SUNJMF
- 64bit + Java + SUNJMF

All tools seem to start okay. BAS audio is all right in all three versions. MPG video loads with 32bit versions and JMF player, but is crappy, at least in VM Ware / Virtual Box. Video does not load with 64bit versions.

**Comment by Herrner** [comment]
1.6 is out in the field now, so closing this.
