### ISSUE TITLE
Bug in EXAKT Annotation Search

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#56]
When the corpus' exs files are pretty printed, EXAKT does:

Exception in thread "Thread-8" java.lang.ClassCastException: org.jdom.Text cannot be cast to org.jdom.Element
	at org.exmaralda.exakt.search.AnnotationSearchResult.<init>(AnnotationSearchResult.java:34)
	at org.exmaralda.exakt.search.XMLSearchableSegment.search(XMLSearchableSegment.java:101)
	at org.exmaralda.exakt.search.XMLCorpusComponent.search(XMLCorpusComponent.java:120)
	at org.exmaralda.exakt.search.Search.doSearch(Search.java:74)
	at org.exmaralda.exakt.exmaraldaSearch.swing.COMAKWICSearchPanel$20.run(COMAKWICSearchPanel.java:1065)

**Comment by berndmoos** [comment]
Should be robust against pretty printing now, @hannahedeland has the test case

**Comment by hannahedeland** [comment]
(after changing the right context too) now the index doesn't fit the list of children anymore

Exception in thread "Thread-5" java.lang.IndexOutOfBoundsException: Index: 63 Size: 63
	at org.jdom.ContentList.get(ContentList.java:377)
	at org.jdom.ContentList$FilterList.get(ContentList.java:582)
	at org.exmaralda.exakt.search.AnnotationSearchResult.<init>(AnnotationSearchResult.java:40)
	at org.exmaralda.exakt.search.XMLSearchableSegment.search(XMLSearchableSegment.java:101)
	at org.exmaralda.exakt.search.XMLCorpusComponent.search(XMLCorpusComponent.java:120)
	at org.exmaralda.exakt.search.Search.doSearch(Search.java:74)
	at org.exmaralda.exakt.exmaraldaSearch.swing.COMAKWICSearchPanel$20.run(COMAKWICSearchPanel.java:1065)
