### ISSUE TITLE
Check MAUS results for stratification?

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#91]
It seems to happen (infrequently) that the results from MAUS contain overlapping segments within a tier. Need a test case. In any case: MAUS result could be checked before it is integrated into the transcription, otherwise:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: cell range R1C1724:R1C1725 overlaps an existing span
	at com.klg.jclass.table.SpanHandler.validateRange(Unknown Source)
	at com.klg.jclass.table.SpanHandler.addSpannedRange(Unknown Source)
	at com.klg.jclass.table.JCTable.addSpannedRange(Unknown Source)
	at org.exmaralda.partitureditor.partiture.PartitureTable.setAllSpans(PartitureTable.java:620)
	at org.exmaralda.partitureditor.partiture.PartitureTable.resetData(PartitureTable.java:192)
	at org.exmaralda.partitureditor.partiture.clarinActions.WebMAUSAction.success(WebMAUSAction.java:294)
	at org.exmaralda.partitureditor.partiture.clarinActions.WebMAUSAction$1$1.run(WebMAUSAction.java:143)
```

**Comment by berndmoos** [comment]
Added a stratification check which will give a message and abort the operation if a MAUS result is not stratified. Don't have a test case, though...
