### ISSUE TITLE
Something is wrong with Playback Mode

### ISSUE THREAD

**Issue by berndmoos** [Exmaralda-Org/exmaralda#98]
* Strange behaviour (and, ultimately: crash) with JDS player and UNSD example
* No problems with BAS player for the same file
* On the MAC: who knows...?

**Comment by berndmoos** [comment]
This happens only when PlaybackMode is activated - but why?

```
Exception in thread "PeriodicUpdateController" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at mpi.eudico.client.mediacontrol.EventPoster.<init>(EventPoster.java:28)
	at mpi.eudico.client.mediacontrol.EventPostingBase.postEvent(EventPostingBase.java:67)
	at mpi.eudico.client.mediacontrol.PeriodicUpdateController.run(PeriodicUpdateController.java:53)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by berndmoos** [comment]
It does not happen when processPlayableEvent in PartitureTableWithActions does not interact with the GUI. Maybe put that in a separate Thread?

**Comment by berndmoos** [comment]
I am a thread magician! This seems to help, need to check if it breaks other things like the BAS player. Must go and see Paul Weller now.

**Comment by berndmoos** [comment]
Tested with latest preview: BAS, JDS, JMF and MMF player all seem to work fine now on windows. Need to check CocoaQT player on MAC before issue can be closed.

**Comment by berndmoos** [comment]
Checked CocoaQT player on MAC - seems to work, too. Käs klosd.
